### ISSUE TITLE
Selecting time point pairs for transition map 

### ISSUE THREAD

**Issue by jindalk** [AllonKleinLab/cospar#13]
Hi,
I am focusing on 3 time points of interest in my dataset, let's say t1, t2, and t3. Ideally, I want to build a transition map using 3 pairs, t1-t2, t2-t3 and t1-t3 transitions. Is there any way I could run that? I could only find ways of doing 2 pairs at a time, either t1-t2, t2-t3 or t1-t2,t1-t3 or t1-t3,t2-t3.

If I do have to choose 2 of the 3 pairs, would you have any recommendations on how to determine what are the 2 best pairs? I would assume choose pairs which have the highest transitions and at least one pair containing t3, since that time point would have the most robust fate information. 

Thanks!

**Comment by ShouWenWang** [comment]
currently, CoSpar operates in only two modes: given t1, t2, t3,  you can learn a map from early time points to late time point (t1-t3, t2-t3), or you can learn a map between neighboring time points (t1-t2, t2-t3).  The first mode is the default, and the second mode is possible only for infer_Tmap_from_multitime_clones. See explanation below (also check the API explanation). If you really want to have t1-t2, t2-t3, t1-t3, you might have to run two computation, and manually stitch the maps together. Let me know if it works for you!


For the second mode, the key parameters are:


  *   clonal_time_points (list; default: all): List of time points with clonal data that you want to perform inference.

  *   later_time_point (str; default: None): If not set, CoSpar learns a transition map between neighboring time points specified by clonal_time_points, i.e., transitions from day 2 to day 4, and from day 4 to day 6 if clonal_time_points=[‘2’,’4’,’6’]. Ohterwise, it learns transitions from any of clonal_time_points to the later_time_point.

Also see the API documentation

https://cospar.readthedocs.io/en/latest/cospar.tmap.infer_Tmap_from_multitime_clones.html#cospar.tmap.infer_Tmap_from_multitime_clones

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: jindalk ***@***.***>
Sent: Thursday, March 31, 2022 9:37:20 AM
To: AllonKleinLab/cospar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AllonKleinLab/cospar] Selecting time point pairs for transition map (Issue #13)


Hi,
I am focusing on 3 time points of interest in my dataset, let's say t1, t2, and t3. Ideally, I want to build a transition map using 3 pairs, t1-t2, t2-t3 and t1-t3 transitions. Is there any way I could run that? I could only find ways of doing 2 pairs at a time, either t1-t2, t2-t3 or t1-t2,t1-t3 or t1-t3,t2-t3.

If I do have to choose 2 of the 3 pairs, would you have any recommendations on how to determine what are the 2 best pairs? I would assume choose pairs which have the highest transitions and at least one pair containing t3, since that time point would have the most robust fate information.

Thanks!

**Comment by jindalk** [comment]
Hi Shou-Wen, I could try stitching maps together, if the either of the default approaches don't work for me. How do I do that? Is it just adding the 2 transition maps?

Thanks

**Comment by jindalk** [comment]
Got it, just one last clarification regarding your earlier comment. If I want to use transitions t1-t3 and t2-t3, are the following  arguments equivalent?

case1: setting clonal_time_points=['t1','t2'] and later_time_points='t3'
case2: setting clonal_time_points=['t1','t2','t3'] and later_time_points='t3'

Reading through the hematopoiesis and reprogramming vignettes, specifically "Part I: Infer transition map using clones from all time points" in each, it seems like you used case 2 in hematopoiesis and case 1 in reprogramming.

Sorry, just want to make sure I get this exactly right.

Thanks!

**Comment by ShouWenWang** [comment]
I think they are equivalent!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
