### ISSUE TITLE
clarification for one time point clone inference

### ISSUE THREAD

**Issue by cnk113** [AllonKleinLab/cospar#23]
Hello,

I have a dataset with multiple time points but I only have two independent time points with clonal information (diff experiment/no barcodes are shared between the two time points). 
It should be fine to run `infer_Tmap_from_one_time_clones` independently where I use all the initial time points with no barcodes and the single time point clonal information?
For example, I have day 5, 10, 15, 20 (with clones)
and the other with:
5, 10, 15, 25 (with clones)
Just to emphasize I don't have clonal info in 5,10,15

Or how else would you recommend running this?

Best,
Chang

**Comment by ShouWenWang** [comment]
You could also run it with 
5, 10, 15, 20 (with clones), 25 (with clones)
in this case, you set initial_time_points=['5','10','15','20'], later_time_point=['25'], so that you will have a transition map from day 20 to day 25 
cospar.tmap.infer_Tmap_from_one_time_clones(adata_orig, initial_time_points=None, later_time_point=None, initialize_method='OT',OT_cost='SPD')

Also, it may be worthwhile to try different parameters, like initialized_method= {‘OT’, ‘HighVar’}, and for OT_cost, try {‘GED’,’SPD’}

Hope this helps!
